services:
  db:
    platform: linux/amd64
    image: postgres:16
    env_file:
      - ./.env
    ports:
      - '5432:5432'
  dashboard:
    platform: linux/amd64
    image: rub21/osm-sandbox-dashboard:v8
    env_file:
      - ./.env
    build:
      context: images/dashboard/
      dockerfile: Dockerfile
    volumes:
      - ./images/dashboard/src:/app
    ports:
      - '8000:8000'
    # working_dir: /app
