environment: production
serviceType: ClusterIP
# createClusterIssuer: true
adminEmail: admin@osmsandbox.us
db:
  enabled: true
  image:
    name: postgres
    tag: 16
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: dashboard-node
  env:
    POSTGRES_DB: db_dashboard
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: {{POSTGRES_PASSWORD}}
  persistenceDisk:
    enabled: true
    accessMode: ReadWriteOnce
    mountPath: /var/lib/postgresql/data
    subPath: postgresql-db
    AWS_ElasticBlockStore_volumeID: vol-033c268be89f2b35f
    AWS_ElasticBlockStore_size: 10Gi
  resources:
    enabled: false
    requests:
      memory: "10Gi"
      cpu: "5"
    limits:
      memory: "10Gi"
      cpu: "5"
  sharedMemorySize: 16Mi
dashboard:
  enabled: true
  ingressDomain: dashboard.osmsandbox.us
  env:
    ENVIRONMENT: production
    #################### Dashboard osm auth  ####################
    OSM_CLIENT_ID: {{OSM_CLIENT_ID}}
    OSM_CLIENT_SECRET: {{OSM_CLIENT_SECRET}}
    REDIRECT_URI: "https://dashboard.osmsandbox.us/redirect_sandbox"
    OSM_INSTANCE_URL: "https://www.openstreetmap.org"
    OSM_INSTANCE_SCOPES: "read_prefs"

    ## Token
    ACCESS_TOKEN_EXPIRE_MINUTES:  1440
    SECRET_KEY: {{SECRET_KEY}}
    
    #################### Sandbox env vars ####################
    OSM_SANDBOX_CHART: https://osm-sandbox.github.io/osm-sandbox-deploy/osm-sandbox-deploy-0.0.1-0.dev.git.1.hda82db6.tgz
    SANDBOX_NAMESPACE: 'default'

    #################### Sandbox Database env vars ####################
    SANDBOX_PG_DB_PORT: "5432"
    SANDBOX_PG_DB_USER: postgres
    SANDBOX_PG_DB_PASSWORD: {{SANDBOX_PG_DB_PASSWORD}}
    SANDBOX_PG_DB_NAME: {{SANDBOX_PG_DB_NAME}}

    #################### Sandbox Api env vars ####################
    SANDBOX_DOMAIN: "boxes.osmsandbox.us"
    SANDBOX_MAILER_ADDRESS: "none"
    SANDBOX_MAILER_DOMAIN: osmsandbox.us
    SANDBOX_MAILER_USERNAME: "none"
    SANDBOX_MAILER_PASSWORD: "none"
    SANDBOX_OSM_id_key: {{SANDBOX_OSM_id_key}}
    SANDBOX_OAUTH_CLIENT_ID: {{SANDBOX_OAUTH_CLIENT_ID}}
    SANDBOX_OAUTH_KEY: {{SANDBOX_OAUTH_KEY}}
    SANDBOX_MAILER_FROM: osm-sandbox-admins@googlegroups.com
    SANDBOX_NOMINATIM_URL: "none"
    SANDBOX_OVERPASS_URL: "none"
    SANDBOX_NEW_RELIC_LICENSE_KEY: "none"
    SANDBOX_NEW_RELIC_APP_NAME: "none"
    SANDBOX_ORGANIZATION_NAME: OpenStreetMap-Sandbox
    SANDBOX_WEBSITE_STATUS: "online"
    SANDBOX_BACKUP_FILE_URL: {{SANDBOX_BACKUP_FILE_URL}}
    SANDBOX_TM_OAUTH_CLIENT_ID: {{SANDBOX_TM_OAUTH_CLIENT_ID}}
    SANDBOX_TM_OAUTH_CLIENT_SECRET_HASHED: {{SANDBOX_TM_OAUTH_CLIENT_SECRET_HASHED}}

  resources:
    enabled: false
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "512Mi"
      cpu: "1"
  nodeSelector:
    enabled: true
    label_key: nodegroup_type
    label_value: dashboard-node
